### ISSUE TITLE
Add CHANGELOG file

### ISSUE THREAD

**Issue by jeremy-w** [shawnthroop/stpnut#2]
See http://keepachangelog.com for advice and format.

**Comment by jeremy-w** [comment]
You can tie issues to the commits that work on them by including tags in the commit message like `[#2]`. You can even close an issue from a commit with `[closes #2]`. This makes it easy to see what changes fixed an issue and vice-versa. (It's a small but significant step towards *requirements traceability.*)

**Comment by shawnthroop** [comment]
@jeremy-w I was looking for buttons to do this on Github. I already committed though and couldn't figure out how to retroactively do it. Another tip in the jar, thanks 😊

**Comment by jeremy-w** [comment]
There's a ton of little things like this that make up a dev workflow. I like git-tracker to make this easy - it'll read the issue ID out of the branch name and then stamp it into the commit message for you as a number formatted like that.

**Comment by shawnthroop** [comment]
@jeremy-w because I'm self taught and work alone I haven't yet been forced to learn how to use systems like git to help facilitate between a team. My one experience with branches wiped out my whole repository until Backblaze came to the rescue. It's not that I don't have a version/bug tracker, I use Notes to keep track of changes and bugs because its more approachable for me.

Is there some resources where this is all codified, or is passed from person to person or through schooling?

**Comment by jeremy-w** [comment]
I think most people pick up a workflow by working on an established project. It could be an open source one with a whole workflow detailed in CONTRIBUTING or by an owning foundation like GNU or Apache, or a closed source one with the related tools and workflows most likely laid out in the README.

I suspect I can find some learning resources though that don't rely on working on a different project, though. I'll try to post some links today.
--
Jeremy W. Sherman
http://jeremywsherman.com/

**Comment by shawnthroop** [comment]
@jeremy-w Thanks!

**Comment by jeremy-w** [comment]
You'll probably want to go snag some example workflows from existing node projects (check their CONTRIBUTING & README docs), but here's some more general info:

- https://opensource.guide/ has a lot of great info written to be very accessible and easy to follow.
- http://producingoss.com/ is written more as a book than as Web material, but it's been around for a long time, has recently been revised, and is rather comprehensive.
- Both of those are focused particularly on open source software. But what about collaborating on software in general? https://faculty.washington.edu/ajko/books/cooperative-software-development/ is a short summary of the human aspects of building software together:

  > After teaching software engineering for many years, I've been frustrated by the lack of a simple, concise, and practical introduction to the human aspects of software engineering for students interested in becoming software engineers.
  >
  > …the chapters … synthesize the broad evidence we have about how teams have to work together to succeed.
