### ISSUE TITLE
Document target node version

### ISSUE THREAD

**Issue by jeremy-w** [shawnthroop/stpnut#3]
Determines stuff like language version. For example I noticed a mix of const and var, no class syntax, etc, leaving me unclear if you're writing against ES5 or ES6.

**Comment by shawnthroop** [comment]
@jeremy-w I'm learning as I write so I'm mostly going off of docs and examples, hence the mix of conventions and uniformity. Where does one define these things?

**Comment by jeremy-w** [comment]
I'd check if package.json supports that, but even if so, definitely document it in the README. Even just "Developed against: node (whatever node --version spits out)" is helpful.
--
Jeremy W. Sherman
http://jeremywsherman.com/

**Comment by jeremy-w** [comment]
Pulling in something like eslint can help with uniformity, as well. (VSCode has really nice integration with it and a subset of JSDoc.)
--
Jeremy W. Sherman
http://jeremywsherman.com/

**Comment by shawnthroop** [comment]
@jeremy-w Some quick research reveals that `package.json` supports an `engine` key where you specify npm and node versions.
