### ISSUE TITLE
Standardize use of camelCase or snake_case for object keys

### ISSUE THREAD

**Issue by jeremy-w** [shawnthroop/stpnut#6]
I noticed README shows both styles in use for different config objects.

**Comment by shawnthroop** [comment]
I like camelCase but the pnut.io API uses snake, for example in the case of 'object_types'. My Objective-C and Swift experience has made me pretty diligent about this when I'm in control of it.

**Comment by jeremy-w** [comment]
Then I recommend going with Pnut's style if you're going to let it shine through. But it's also doable to just rekey it before passing it along to Pnut. Key-style changimg string munging functions are pretty common; I know Ember has them to dasherize/camel-case keys as needed.
